const { alumnoActivo, normalizarTelefonoPeru, saldoPension, compromisoVigente, crearMensaje, crearEnlace } = require('../utils/cobranzaMensajeria');
describe('cobranzaMensajeria', () => {
  test('normaliza celulares peruanos', () => { expect(normalizarTelefonoPeru('946 413 462')).toBe('51946413462'); expect(normalizarTelefonoPeru('+51 946-413-462')).toBe('51946413462'); expect(normalizarTelefonoPeru('123')).toBeNull(); });
  test('calcula saldo', () => { expect(saldoPension({ monto_total: '450', monto_pagado: '100' })).toBe(350); expect(saldoPension({ monto_total: '450', monto_pagado: '500' })).toBe(0); });
  test('solo considera alumnos activos para cobranza', () => { expect(alumnoActivo({ estado: 'ACTIVO' })).toBe(true); expect(alumnoActivo({ estado: 'RETIRADO' })).toBe(false); expect(alumnoActivo({ estado: 'DELETED' })).toBe(false); });
  test('respeta compromisos vigentes', () => { const now = new Date('2026-08-24T12:00:00-05:00'); expect(compromisoVigente([{ estado: 'VIGENTE', fecha_compromiso: '2026-08-25' }], now)).toBeTruthy(); expect(compromisoVigente([{ estado: 'VIGENTE', fecha_compromiso: '2026-08-23' }], now)).toBeNull(); });
  test('crea enlaces WhatsApp y SMS', () => { const mensaje = crearMensaje({ canal: 'SMS', colegio: 'COLEGIO HARVARD', alumno: 'Juan Perez', mes: 'AGO', saldo: 450 }); expect(mensaje).toContain('S/450'); expect(crearEnlace('WHATSAPP', '51946413462', 'Hola')).toBe('https://wa.me/51946413462?text=Hola'); expect(crearEnlace('SMS', '51946413462', 'Hola')).toBe('sms:+51946413462?body=Hola'); });
  test('agrupa solo los conceptos seleccionados en un mensaje', () => { const mensaje = crearMensaje({ canal: 'WHATSAPP', colegio: 'COLEGIO HARVARD', alumno: 'Juan Perez', conceptos: [{ clave_mes: 'JUL', saldo: 100 }, { clave_mes: 'AGO', saldo: 150 }] }); expect(mensaje).toContain('JUL: S/100'); expect(mensaje).toContain('AGO: S/150'); expect(mensaje).toContain('Total: S/250'); });
  test('firma el recordatorio con la institución configurada', () => { const mensaje = crearMensaje({ canal: 'WHATSAPP', colegio: 'COLEGIO HARVARD', alumno: 'Juan Perez', mes: 'AGO', saldo: 280 }); expect(mensaje).toContain('COLEGIO HARVARD.'); expect(mensaje).not.toContain('Colegio Fernando'); });
  test('usa una redacción natural para los pagos pendientes', () => { const mensaje = crearMensaje({ canal: 'WHATSAPP', colegio: 'COLEGIO HARVARD', alumno: 'Fátima', mes: 'AGO', saldo: 280 }); expect(mensaje).toContain('le recordamos los pagos pendientes de Fátima'); expect(mensaje).not.toContain('conceptos seleccionados pendientes'); });
});

