const CANALES = new Set(['WHATSAPP', 'SMS']);
const ESTADOS_ENVIO = new Set(['PREPARADO', 'ABIERTO', 'CONFIRMADO', 'NO_ENVIADO', 'OMITIDO', 'FALLIDO']);
const ESTADOS_COMPROMISO = new Set(['VIGENTE', 'CUMPLIDO', 'VENCIDO', 'CANCELADO']);
function alumnoActivo(alumno) { return String(alumno?.estado || '').toUpperCase() === 'ACTIVO'; }
function normalizarTelefonoPeru(value) { const digits = String(value || '').replace(/\D/g, ''); if (/^9\d{8}$/.test(digits)) return `51${digits}`; if (/^519\d{8}$/.test(digits)) return digits; return null; }
function saldoPension(estado) { return Math.max(0, Number((Number(estado.monto_total || 0) - Number(estado.monto_pagado || 0)).toFixed(2))); }
function compromisoVigente(compromisos, now = new Date()) { const hoy = new Date(now); hoy.setHours(0, 0, 0, 0); return (compromisos || []).find((c) => { const fecha = new Date(c.fecha_compromiso); fecha.setHours(0, 0, 0, 0); return c.estado === 'VIGENTE' && fecha >= hoy; }) || null; }
function formatoMonto(value) { return Number(value).toLocaleString('es-PE', { minimumFractionDigits: 0, maximumFractionDigits: 2 }); }
function crearMensaje({ canal, colegio, alumno, mes, saldo, conceptos, telefonoContacto }) { if (!CANALES.has(canal)) throw new Error('Canal no válido'); const seleccion = conceptos?.length ? conceptos : [{ clave_mes: mes, saldo }]; const detalle = seleccion.map((x) => `${x.concepto || x.clave_mes}: S/${formatoMonto(x.saldo)}`).join(', '); const total = seleccion.reduce((s, x) => s + Number(x.saldo || 0), 0); if (canal === 'SMS') return `${colegio}: pagos pendientes de ${alumno}: ${detalle}. Total S/${formatoMonto(total)}. Si ya pagó, ignore este SMS. Consultas: ${telefonoContacto || ''}`.trim(); return `Estimado(a) apoderado(a), le recordamos los pagos pendientes de ${alumno}: ${detalle}. Total: S/${formatoMonto(total)}. Si ya realizó el pago, ignore este mensaje o envíenos su comprobante. ${colegio}.`; }
function crearEnlace(canal, telefono, mensaje) { const encoded = encodeURIComponent(mensaje); if (canal === 'WHATSAPP') return `https://wa.me/${telefono}?text=${encoded}`; if (canal === 'SMS') return `sms:+${telefono}?body=${encoded}`; throw new Error('Canal no valido'); }
function crearMensajeNivel(datos, nivel = 1) {
  if (![1, 2, 3, 4].includes(nivel)) throw new Error('Nivel no válido');
  if (nivel === 1 || datos.canal === 'SMS') return crearMensaje(datos);
  const conceptos = (datos.conceptos || []).filter(x => Number(x.saldo) > 0);
  const detalle = conceptos.map(x => `${x.concepto || x.clave_mes}: S/${formatoMonto(x.saldo)}`).join('\n');
  const total = formatoMonto(conceptos.reduce((s, x) => s + Number(x.saldo), 0));
  const deuda = `${detalle}\n\nTotal pendiente: S/${total}.`;
  if (nivel === 2) return `Estimado(a) apoderado(a):\n\nNos comunicamos nuevamente con usted debido a que continúan pendientes los siguientes pagos correspondientes a ${datos.alumno}:\n\n${deuda}\n\nLe solicitamos regularizar estos pagos a la brevedad posible. Agradecemos tomar las previsiones necesarias para cumplir con sus obligaciones pendientes con la institución.\n\nSi ya realizó el pago, por favor envíenos su comprobante para actualizar nuestros registros.\n\nCOLEGIO HARVARD.`;
  if (nivel === 3) return `Estimado(a) padre, madre de familia o apoderado(a):\n\nReciba un cordial saludo. Nos comunicamos con usted debido a que, a la fecha, mantiene pagos pendientes con nuestra institución correspondientes a ${datos.alumno}.\n\n${deuda}\n\nPor tal motivo, le solicitamos acercarse de manera obligatoria al colegio el día de mañana, en el horario de ingreso, acompañado de su menor hijo(a), a fin de regularizar su situación de pagos y realizar las coordinaciones correspondientes.\n\nAgradecemos de antemano su puntual asistencia y comprensión.\n\nDirección – Colegio Harvard.`;
  return `Estimado(a) padre, madre de familia o apoderado(a):\n\nReciba un cordial saludo. Nos comunicamos con usted nuevamente debido a que, pese a los avisos y coordinaciones previas realizadas, a la fecha se mantienen pagos pendientes correspondientes a ${datos.alumno}.\n\n${deuda}\n\nPor tal motivo, le solicitamos regularizar esta situación de manera inmediata y acercarse personalmente a la institución para realizar las coordinaciones correspondientes.\n\nEste mensaje constituye un último aviso de regularización, por lo que agradeceremos atenderlo con carácter prioritario y comunicarse con la Dirección del colegio a la brevedad.\n\nSi ya realizó el pago, por favor envíenos su comprobante para actualizar nuestros registros.\n\nDirección – Colegio Harvard.`;
}
module.exports = { CANALES, ESTADOS_ENVIO, ESTADOS_COMPROMISO, alumnoActivo, normalizarTelefonoPeru, saldoPension, compromisoVigente, crearMensaje, crearMensajeNivel, crearEnlace };

